# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Billboardoo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Billboardoo
  pod 'RxSwift', '6.5.0'
  pod 'RxCocoa', '6.5.0'
  pod 'NavigationBarColor'

 #login sdk
 pod 'naveridlogin-sdk-ios'
  
target 'BillboardooTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'BillboardooUITests' do
    # Pods for testing
  end

end
