name: Run build

on:
# develop 브랜치에 push, pull_request Event 발생 시 jobs를 실행합니다.
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

# Workflow가 실행할 jobs
jobs:
  build:
    # job이 실행될 환경: https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners 
    # macOS Big Sur 11
    # macos-latest OR macos-11
    runs-on: macos-12 

    # job의 일부로 실행될 일런의 task
    steps: 

# 워크플로에서 액세스할 수 있도록 에서 저장소를 체크아웃
    - uses: actions/checkout@v3
    
    - name: Cache Primes
      id: cache-primes
      uses: actions/cache@v3
      with:
        path: /Users/runner/Library/Developer/Xcode/DerivedData/**/SourcePackages/checkouts 
        key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }} # Package.resolved => 버전정보
    
    - name: Decrypt file

      env:
        ENCRYPTED_SECURITY_FILE_PATH: ${{ '.github/secrets/Security.xcconfig.gpg' }}
        DECRYPTED_SECURITY_FILE_PATH: ${{ 'WaktaverseMusic/Security.xcconfig' }}
        SECURITY_ENCRYPTION_KEY: ${{ secrets.SECURITY_KEY }} 
      run: |  
        gpg -d -o "$DECRYPTED_SECURITY_FILE_PATH" --pinentry-mode=loopback --passphrase "$SECURITY_ENCRYPTION_KEY" "$ENCRYPTED_SECURITY_FILE_PATH"


    
    - name: Force Xcode 13
      run: sudo xcode-select -s /Applications/Xcode_13.4.1.app

       
    - name: Start Xcode build
      run: |
        xcodebuild clean build -project WaktaverseMusic/WaktaverseMusic.xcodeproj -scheme WaktaverseMusic -destination 'platform=iOS Simulator,name=iPhone 13 Pro Max,OS=15.5'
